### ISSUE TITLE
XML Error on Server Crash

### ISSUE THREAD

**Issue by DrewBarclay** [pontarius/pontarius-xmpp#88] opened 2015-05-14 04:23 UTC
When our XMPP server crashed, the bot hooked up to it failed to reconnect when it was restarted. Looking at it, it seems it had an exception due to the XML (see screenshot). This seems to be a Pontarius-specific issue, rather than one related to my code.
![untitled](https://cloud.githubusercontent.com/assets/12365025/7626070/1daa58a6-f9c7-11e4-849c-8f83b66df790.png)

**Comment by jonkri** [comment] 2015-07-26 23:59
Thank you for creating this issue! This indeed looks like a bug in Pontarius XMPP. I'm quite busy these days, so I'm not quite sure when/if I could take a look at this. If you would like to investigate the issue yourself, pull requests are of course always welcome.

**Comment by Philonous** [comment] 2015-11-16 18:59
I reproduced this and am looking into it

**Comment by Philonous** [comment] 2015-11-23 13:25
Should be fixed

**Closed by Philonous** 2015-11-23 13:25 UTC
Labels: bug
